### PR TITLE
Added Dockerfile - csharp book

### PR DESCRIPTION
**Pull request by wjdavis5**

### CODE REVIEW

**Comment by caio-ribeiro-pereira** [comment]
@wjdavis5 why dockerfile? it's only a simple website, could you remove it?

**Comment by wjdavis5** [comment]
I added the docker file b/c of the dependency on a rather old version of node js. The only way to host and run this thing locally was to either use a container, or blow away my own docker version.

Now you can run:

```
docker build -t yourname/devfreebooks:latest .
docker run -t -i -p=3000:3000 yourname/devfreebooks:latest
```

and have a working copy of this site running.

**Comment by caio-ribeiro-pereira** [comment]
yesterday I updated all modules to run this site into lastest version of nodejs.

**Comment by caio-ribeiro-pereira** [comment]
I will accept your PR, but I will remove the dockerfile, because there is no need to run old node version anymore, thanks!

**Comment by wjdavis5** [comment]
merged in your latest - removed docker files.

**Comment by caio-ribeiro-pereira** [comment]
Thanks

**Pull request merged**
